# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The base URL of the site; the only required configuration variable.
base_url = "https://grodino.github.io"

# The theme
theme = "hyde"

# The site title and description; used in feeds by default.
title = "Augustin Godinot"
description = "ğŸšµ PhD student @ INRIA \n ğŸ‘¨â€ğŸ“ prev. ENS Paris-Saclay"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = true

[extra]
hyde_links = [
    {url = "https://github.com/grodino", name = "ğŸ’» Github"},
    {url = "https://www.linkedin.com/in/augustingodinot/", name = "ğŸ“„ Linkedin"},
]